### ISSUE TITLE
Add confetti to `og:image` and web page on CWV pass & 100/100 scores 🟢

### ISSUE THREAD

**Issue by danielroe** [danielroe/page-speed.dev#14]
### Suggested improvements 🔨 

When a domain returns with all green scores, confetti should appear on the web page. Moreover, when sharing a URL on social media, the `og:image` should display confetti.

### References 📖 

https://x.com/jh3yy/status/1756415574110880075?s=46
https://github.com/PuruVJ/neoconfetti/tree/main/packages/vue

**Comment by JamieSlome** [comment]
Do we want the confetti applied to the `og:image`?

**Comment by danielroe** [comment]
As well as the page?

Amazing idea. 🤯

**Comment by JamieSlome** [comment]
@danielroe - what should we say is the criteria for displaying the confetti on page and `og:image`?

**Comment by danielroe** [comment]
We could start off with CWV pass and all 100 Lighthouse scores?

**Comment by JamieSlome** [comment]
> We could start off with CWV pass and all 100 Lighthouse scores?

Sounds good 👍
