### ISSUE TITLE
doesnt work with subdomains

### ISSUE THREAD

**Issue by titoBouzout** [danielroe/page-speed.dev#22]
It doesn't seem to be working with subdomains https://page-speed.dev/pota.quack.uy

**Comment by danielroe** [comment]
That seems to be working for me...
![CleanShot 2024-02-12 at 23 03 50@2x](https://github.com/danielroe/page-speed.dev/assets/28706372/dda54727-95f4-4bbe-8029-b6f14f86d321)

**Comment by titoBouzout** [comment]
Something must have changed because it was saying the domain was invalid
