### ISSUE TITLE
Option to select which device type you want to audit

### ISSUE THREAD

**Issue by Baroshem** [danielroe/page-speed.dev#6]
Hey there Daniel!

Great idea, we are using something similar at VSF for our Console 🚀

One addition that might be useful is to add an ability to select which device type (mobile or desktop) you want to audit (for now it is mobile by default).

Maybe we could also add an option to do audits for both devices at the same time if both options are selected and display basically two results (one after another)?

Let me know your thoughts 😉

**Comment by danielroe** [comment]
Thank you for the idea! ❤️

I'd be up for a client-side switch to see desktop, but the scores are too easy to get good results for, so I think I wouldn't like to allow them to be shared, seen by default, or included in OG images.

**Comment by Baroshem** [comment]
Yes, we can keep it like this (so mobile will be used by default) but I think that the ability to see also the result of desktop (to be able to compare how the app behaves on both device types) can be useful for some applications.

I am up for creating a PR with this feature if you agree but first, I would prefer to consult with you how this should be implemented.

My idea was that in the first screen (where we provide a domian to audit) we could add a checkbox named for example `include desktop results`. Then, in the second screen where would be a result of CWV and Lighthouse for mobile, also a result for desktop would be displayed but it wont be included in the OG Image.

Would that work?

**Comment by danielroe** [comment]
I think we should fetch data for desktop as well in the initial dataset so it can be cached.

then have an icon that allows swapping data view to desktop.

**Comment by Baroshem** [comment]
Ok, so I will fork the repo and work on it next week :) 

Thanks for your view on this, I will implement it this way
