### ISSUE TITLE
Pop up boxes fail to disappear on focus change on mobile 🤙

### ISSUE THREAD

**Issue by JamieSlome** [danielroe/page-speed.dev#8]
### Reproduce the bug ⚡️

When interacting with the results section on mobile, press any of the dashed underlined titles.

Note, if you change focus to an interactive or clickable element, the pop up box disappears.

### Suggested improvements 🔨

The pop up box should disappear when focus changes to any element other than the pop up box itself.

### Device and Browser 📱

iPhone, Safari

**Comment by JamieSlome** [comment]
@danielroe - happy to take this on 👍

**Comment by danielroe** [comment]
Amazing - thank you! ❤️

**Comment by JamieSlome** [comment]
So the bug doesn't appear consistent 🤔 

Struggling with reproducibility on browser emulator but certainly still facing the same issue on Safari directly on mobile device:

https://github.com/danielroe/page-speed.dev/assets/55323451/ece515e2-82ab-45b9-9976-2961ad0f80c6

**Comment by JamieSlome** [comment]
Confirmed as a Safari specific issue. Works perfectly on Google Chrome on device same device.

Why Safari, why? 😢

**Comment by danielroe** [comment]
😰

**Comment by JamieSlome** [comment]
So, trivially, I've tried multiple event triggers to force the tooltip to close. Sadly, these don't quite hit the mark. It looks like a globally accepted issue with iOS (https://github.com/twbs/bootstrap/issues/16028).

@danielroe; I can implement a close button at the top-right of the pop-ups on `sm` viewports? Or just implement a different type of element to load with explicit function calls to invoke the appearance and disappearance of the element for `sm` viewports?
